# Generated by Django 3.0.3 on 2021-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianinfo',
            name='student_reg_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
