# Generated by Django 3.0.3 on 2021-04-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0003_auto_20210423_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianinfo',
            name='annual_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='blood_group',
            field=models.CharField(choices=[(1, 'A(+ve)'), (2, 'A(-ve)'), (3, 'B(+ve)'), (4, 'B(-ve)'), (5, 'AB(+ve)'), (6, 'AB(-ve)'), (7, 'O(+ve)'), (8, 'O(-ve)')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='guardianship_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='nationality',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='office_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='permanent_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='phone_number_home',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='phone_number_office',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='present_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='profession',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='relation_with_student',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='religion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
