# Generated by Django 3.0.3 on 2021-04-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0004_auto_20210423_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardianinfo',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='guardianship_type',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='phone_number_home',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='phone_number_office',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='present_address',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='relation_with_student',
        ),
        migrations.RemoveField(
            model_name='guardianinfo',
            name='religion',
        ),
    ]
