# Generated by Django 3.0.3 on 2021-04-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0005_auto_20210423_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianinfo',
            name='blood_group',
            field=models.PositiveIntegerField(choices=[(1, 'A(+ve)'), (2, 'A(-ve)'), (3, 'B(+ve)'), (4, 'B(-ve)'), (5, 'AB(+ve)'), (6, 'AB(-ve)'), (7, 'O(+ve)'), (8, 'O(-ve)')], null=True, verbose_name='Blood Group'),
        ),
    ]
