# Generated by Django 3.0.3 on 2021-04-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0006_guardianinfo_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianinfo',
            name='annual_income',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='guardianship_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='nationality',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='relation_with_student',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='religion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
