# Generated by Django 3.0.3 on 2021-04-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0007_auto_20210423_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianinfo',
            name='office_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='permanent_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='phone_number_home',
            field=models.CharField(default=0, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='phone_number_office',
            field=models.CharField(default=0, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='present_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='profession',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
